# Generated by Django 2.0.3 on 2018-04-26 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='发表时间')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发表')),
                ('readed_nums', models.IntegerField(default=0, verbose_name='浏览量')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                             to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章列表',
                'verbose_name_plural': '文章列表',
                'ordering': ['-last_update_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30, verbose_name='标签名称')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                              to='blog.Article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '标签组',
                'verbose_name_plural': '标签组',
            },
        ),
    ]
